### ISSUE TITLE
Add paging to list module

### ISSUE THREAD

**Issue by rikkertkoppes** [FirstLegoLeague/displaySystem#10]
Add automatic paging when the number of pasted tows exceeds 10. Make the timeout configurable.

**Comment by Jheronymus** [comment]
Some other features needed in this module:
1. There should be a 'cycle' button in the control window to go faster then the timeout.
2. Maybe a checkbox to enable continues looping. (should work runtime, not exclusively on initiation)
3. The module should also expose page numbers and total pages to the template
4. The module should expose the highscore to the template (as reference score in other pages)

Perhaps better to develop this a separate module: paging-list

**Comment by rikkertkoppes** [comment]
Ad 4: I think the list module should be content agnostic. Just show the pasted content as best as possible.

For the other ideas: all are reasonable.

**Comment by Jheronymus** [comment]
OK, sure. then there should be a ranking module that has this feature. Take a look at a https://youtu.be/VWfQyGPSX8g?t=287
The highscore is small on the second page, but it puts the current page into context.

**Comment by rikkertkoppes** [comment]
I like the way how the next page scrolls up in that example.

Maybe we could add a generic way to "lock" the top row (or x rows), a bit like excel can do. I just wonder what number of rows to display on the first and second page in that case

**Comment by Jheronymus** [comment]
that is why most TV stations just show the current 'score to beat' as additional information on the other pages.
Similar features are the ability to show a world record or tournament highscore.
