### ISSUE TITLE
Curtain needs revisit

### ISSUE THREAD

**Issue by rikkertkoppes** [FirstLegoLeague/displaySystem#13]
2b9b4717d1e95c4387448bdcbbc3d3ca48c0d014

Nice idea, but it breaks some things. For example in a caspar overlay, where the background should actually be transparent, this adds a white flash during loading of the page.

Maybe another approach is to work with body opacity or visibility, both create a properly sized element (in contrast with display:none), but do hide it.

**Comment by Jheronymus** [comment]
Visibility works. It makes the whole thing transparant, so If you would use it in an overlay system, you would see through the whole weblayer during initialization.Funny enough, it will show a background color set to the body tag. So even when used directly as a source for chromakeying, it will work nicely.
