### ISSUE TITLE
https required for webcam access in Chrome

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/displaySystem#18]
https is required to use webcam, but also requires all other calls to be made on secure connections (ws?)

**Comment by rikkertkoppes** [comment]
see https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

the link is changed to https quite a while ago. You now get a mixed content warning. This is easily solved by disabling the camera module for the web instance, however, that's one of the killer features for the hosted solution

The other option would be to change the websocket connection to a secure connection. I have created a feature request at mhub: https://github.com/poelstra/mhub/issues/9

**Comment by rikkertkoppes** [comment]
Online websocket is by default over a secure connection now. Amended readme to explain
