### ISSUE TITLE
Display sponsor logo's

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/displaySystem#19]
Option to display sponsor logo's, either a small icons (so called 'bugs' in AV) and/or full screen as a dedicated sponsor display (for example rotating). 

Ideally users can upload PNGs and order their logo's (assign an importance). and group logo's. See: http://championship.usfirst.org/about-first/championship-sponsors
(platinum, gold, silver etc)

**Comment by rikkertkoppes** [comment]
I'd opt for a (very) simple module that implements showing images as a gallery or stack. With some options for transitions in the config, and an api to set a specific image or rotate to next or previous.

Ordering and grouping of 'bugs' is then a matter outside the scope of the system, just create an image (which may be partially transparent).

Also note that you can already add some stuff in a way, by adjusting the stylesheet, but this is less user friendly

**Comment by rikkertkoppes** [comment]
I implemented a very simple gallery module that does this. However, I'd like to have a simple option to add images to an existing set by just dropping them somewhere. For example a shared dropbox folder, google drive folder, flickr account or something.

If there are any good idea's, third party applications, I'd like to hear it. (@poelstra any ideas maybe?)

**Comment by poelstra** [comment]
@rikkertkoppes Other than the things you mentioned, not really. Other than uploading them to the server.

In all previous years though, we only displayed all sponsors at the same time, as one nearly-fullscreen-image with larger and smaller logo's depending on their 'importance'. This image has traditionally been hand-made in Photoshop.

We also had a similar image with a "thank you" to all volunteers (and all of their names). Maybe good to have a similar feature in the new system, too.

**Comment by rikkertkoppes** [comment]
@kmeesters closing this. I feel we sufficiently support this now with the gallery module. Online image hosting should not be a problem. I added some links in the readme
