### ISSUE TITLE
add script loading for modules

### ISSUE THREAD

**Issue by Jheronymus** [FirstLegoLeague/displaySystem#22]
modules can have their unique stylesheets included. Perhaps something similar can be made to include additional script libraries. The current script loader needs to loop over all modules to make sure these scripts are loaded first.

**Comment by rikkertkoppes** [comment]
This is now added. A module can call `displaySystem.loadScript(src, callback)` and behave accordingly. For example, it can delay its own initialization until the callback

Css files can also be loaded that way, but we don't have a callback for that

For an example, see the emojione module
