### ISSUE TITLE
tweets are displayed by their own and start scrolling from the left

### ISSUE THREAD

**Issue by Jheronymus** [FirstLegoLeague/displaySystem#3]
When you add one or more tweets via the twitter add command, they are not displayed on a single long line, but appear by their own.
They also strart scrolling on the left (instead of starting on the right and scrolling to the left.

**Comment by rikkertkoppes** [comment]
Any screen shot? Sounds weird, which browser?

**Comment by Jheronymus** [comment]
![tweetbug](https://cloud.githubusercontent.com/assets/2046231/7422170/041f9d7e-ef8b-11e4-968d-58bb49ba58c3.png)
succesive tweets will appear in the same way, not like a long line.

**Comment by rikkertkoppes** [comment]
Ah, I see what you mean. They appear mid screen, while it is expected they should scroll into view, right?

**Comment by Jheronymus** [comment]
Just accidently resized the browser, that fixes it. There was only one tweet and it started scrolling from right to left and it was on the screen multiple times to fill the line. I set the window back to full screen (1920x1080) and in continued to work.
When I added another tweet it was not included on the line untill I resized the window again....

**Comment by Jheronymus** [comment]
In the twiter module the getScreenWidth() function gets the wrong value at startup (0 instead of 1920) This is because the body element is hidden during initialization so it has no size.
