### ISSUE TITLE
Misaligned scores in broadcast scoring list / excel pasted values

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/displaySystem#30]
The scores are misaligned in the scoring list. This happens both with scores directly broadcast from the scoring application and if lists are pasted from Excel: 

![capture](https://cloud.githubusercontent.com/assets/5251436/19835798/7d3e3a84-9e90-11e6-87ee-8fc37c3de869.PNG)

Test data: http://uae.scoring.fll-tools.com

**Comment by rikkertkoppes** [comment]
Current workaround: use the table module.

**Comment by rikkertkoppes** [comment]
List module is now updated and much better suited for this purpose

![image](https://user-images.githubusercontent.com/302821/29068341-a091b1da-7c36-11e7-81f4-8c8db1b620ef.png)

With rednblue-plus even more fancy

![image](https://user-images.githubusercontent.com/302821/29068380-d5e47494-7c36-11e7-9db0-dce8cff24ab9.png)
