### ISSUE TITLE
displaySystem needs to have option to show all scores as well as highest

### ISSUE THREAD

**Issue by alanggreen** [FirstLegoLeague/displaySystem#32]
The display should show the scores for all the rounds completed so far, as well as the team's highest score.
![image](https://user-images.githubusercontent.com/6757517/27510582-be30ea04-591c-11e7-9371-28ecafd81be7.png)
**Display from Danny Diaz's scoring system**

If some regions prefer the way the display works currently then this needs to be configurable. 
Maybe this also brings up the requirement for a configuration service so that all configurations are in one place.
@yosikarl @idanstark42

**Comment by rikkertkoppes** [comment]
Please see my extensive answer here: https://github.com/FirstLegoLeague/displaySystem/issues/31

The same reasoning applies, I'd like to have no FLL logic in display system. For this specific use case, the approach would be to push the data of all rounds from fllscoring into displaysystem.

That said, we may need a brush up of the list component, which is less than ideal for displaying multiple columns of data
