### ISSUE TITLE
When no style sheets are set, styles are cleared

### ISSUE THREAD

**Issue by Jheronymus** [FirstLegoLeague/displaySystem#4]
When you hit the set button for the style module, all styles are cleared.

This is probably due to it being set to a null style sheet and reverting to browser defaults.
A more logical action would be a reset to the displaySystem default styles.

**Comment by rikkertkoppes** [comment]
It's only in the config panel for the hosted version. I think it's unlikely you should want to change the style during operation right?

Maybe pressing set with an empty textbox should just do nothing?
