### ISSUE TITLE
Camera module not working

### ISSUE THREAD

**Issue by Jheronymus** [FirstLegoLeague/displaySystem#5]
In the github.io version the camera modules is not working.

consolse shows: could not capture video.(camera.js:38)

hide and show buttons are not responsive and no further messages are logged

the browser is not asking for permission anymore.. is it possible I disabled it permently? Module should check for this.

**Comment by Jheronymus** [comment]
OK, my problem is due to the permission error.
It's now working again. Maybe implement a more 'visual' error system than console logging.

**Comment by rikkertkoppes** [comment]
Good idea, will do
