### ISSUE TITLE
Make the control window a module

### ISSUE THREAD

**Issue by rikkertkoppes** [FirstLegoLeague/displaySystem#8]
May simplify things a bit

**Comment by rikkertkoppes** [comment]
Opening the window is now handled in the config, which is a bit ugly. Would be better to have

```
controls.open()
```

there

**Comment by Jheronymus** [comment]
It wil also make it easier for others to implement their own version of a control window.
Over time we will develop a lot of modules, so the ability to custom the control window and it's input fields will be nice
